config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show]
  
        #"deep nesting"
  # resources :topics do
  #   resources :posts, except: [:index] do
  #     resources :comments, only: [:create, :destroy]
  #   end
  # end

        # "shallow nesting"
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do # [] creates /posts/:post_id/comments and prevents posts/:id
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end



  get 'about' => 'welcome#about'

  root to: 'welcome#index'
  #root is a method that takes a hash as a an argument
  #  root({to: 'welcome#index'})
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  scope :visible_to, -> (user) { user ? all : where(public: true) } #if else statement in brackets {if_this_is_a_true_value ? then_the_result_is_this : else_it_is_this}

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 10)
    authorize @topics
    # raise Pundit::NotAuthorizedError unless TopicPolicy.new(current_user, @topics).index?
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(page: params[:page], per_page: 4)
    authorize @topic
    # raise Pundit::NotAuthorizedError unless TopicPolicy.new(current_user, @topic).index?
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      redirect_to @topic, notice: "Topic was save successfully."
    else
      flash[:error] = "Error creating topic. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{name}\" was successfully deleted"
      redirect_to topics_path
    else
      flash[:error] = "Error deleting Topic."
      render :show
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>

      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topic
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>

</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
    <div class="col-md-8">
      <% @topics.each do |topic| %>
      <div class="media">
          <div class="media-body">
            <h4>
              <%= link_to topic.name, topic %>
            </h4>
            <small>
              <%= topic.description %>
            </small>
          </div>
        </div>
        <% end %>
      <%= will_paginate @topics %>
    </div>

    <div class="col-md-8">
      <% if policy(Topic.new).create? %>
        <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
      <% end %> 
    </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>


<div class="row">

  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%=form_for @topic do |f| %>

      <div class="form_group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>

      <div class="form_group">
        <%= f.label :description %>
        <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
      </div>

      <div class="form_group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public topics
        <% end %> 
      </div>

      <%= f.submit "Save", class: 'btn-success' %>
      
    <% end %>

  </div>

</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <!-- if confused about rendering the 'posts/_post.html.erb partial' see: 'http://guides.rubyonrails.org/layouts_and_rendering.html#rendering-collections' --> 
    <%= render @posts %>
    <%= will_paginate @posts %>
  </div>
  <div>
    <% if policy(Post.new).create? %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
    <% end %>
  </div>
  <div>
    <% if policy(@topic).destroy? %>
      <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic'} %>
          <!-- method: :delete is used to explicitly send an HTTP DELETE request. -->
    <% end %>
  </div>
</div>